### ISSUE TITLE
"clear output" command

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#1]
It would be nice to have a button that clears the output panel, so users can have a clean slate but work from the same code.

**Comment by mhuebert** [comment]
Good idea.

the eval log can be cleared via:

```
(d/transact! [[:db/update-attr :repl/state :eval-log empty]])

```

That can be tested in the REPL, if you first run: `(require '[re-db.d :as
d])`

(But it will show the return value of the transaction, which currently
shows 'error printing result')

**Comment by daveliepmann** [comment]
I'll give that a shot!

**Comment by mhuebert** [comment]
I was doing some UI work, and made room for a toolbar at the bottom of the repl where stuff like this can go:

https://github.com/mhuebert/maria/blob/c6c58e7cffeec324b6b895ea99039ec6ba64efd2/src/maria/views/repl_layout.cljs#L78

I'm not sure how approachable styling is, given that I'm using [Tachyons](tachyons.io/docs/) for all the layout. It's nice when you get the hang of it, but not easy to parse at first. But for buttons etc. we can use re-view-material [components](https://www.re-view.io/components) which should be easier.

**Comment by mhuebert** [comment]
Options...

1. Add a drop-down menu (maybe with a 'settings' icon) to one of the corners of the output section
2. Add a toolbar to the top or bottom of the output section
3. Add a key-command for this

**Comment by jackrusher** [comment]
My preference is obviously for a searchable function in the `M-x` sense (you mentioned sublime has the same sort of thing), which is also bound to a key by default.

**Comment by mhuebert** [comment]
OK, let's start by implementing it as a command & then if we still have the need for a graphical UI later, we can revisit.
