### ISSUE TITLE
Breadcrumb breaks when showing "root"

### ISSUE THREAD

**Issue by pedrorgirardi** [mhuebert/maria#100]
It's a very small thing, but the breadcrumb breaks when its path has only a root node:

![screen shot 2017-09-14 at 08 59 17](https://user-images.githubusercontent.com/585191/30428780-430a0262-992b-11e7-951f-30797b581c27.png)

![screen shot 2017-09-14 at 08 59 24](https://user-images.githubusercontent.com/585191/30428781-4328a3ac-992b-11e7-83f8-f69bda118d10.png)

![screen shot 2017-09-14 at 09 05 09](https://user-images.githubusercontent.com/585191/30428929-db8d007a-992b-11e7-99c3-93a311e059e2.png)

![screen shot 2017-09-14 at 09 05 15](https://user-images.githubusercontent.com/585191/30428930-db8fa4e2-992b-11e7-83a7-ebde234b7acd.png)

**Comment by mhuebert** [comment]
Fixed in 959fd61a257b8359bfe99ff507a2566ee6431261
