### ISSUE TITLE
Commands search with some kind of page indicator

### ISSUE THREAD

**Issue by pedrorgirardi** [mhuebert/maria#101]
What you think about showing some kind of "current page" indicator in the command search? Each "page" shows at most nine commands, and there is no indicator of how much more pages are available. Also when navigating with the arrows keys ⬇️  ⬆️  it's hard to know where we are:

![screen shot 2017-09-14 at 10 44 47](https://user-images.githubusercontent.com/585191/30433062-e071e1ce-9939-11e7-9c96-e100102a76b3.png)

**Comment by mhuebert** [comment]
I'm not entirely sure if we will always know the total # of items in a list, but for times when we do, maybe showing pages as dots could work:

![image](https://user-images.githubusercontent.com/165223/30441511-f6054b44-9979-11e7-8641-98b99f5a69bc.png)

**Comment by pedrorgirardi** [comment]
It does look very nice and it addresses both of the issues I mentioned, and I can't think in a better UI. I liked it!

**Comment by pedrorgirardi** [comment]
I think it will feel better too. Currently when we navigate to the next page it UI moves slightly to place the arrow on the top.
