### ISSUE TITLE
support multiple local-only unsaved docs

### ISSUE THREAD

**Issue by mhuebert** [mhuebert/maria#102]
it is not yet possible to have multiple docs which are only locally persisted. there is only one slot for the currently unsaved doc, which is always re-used when navigating to '/new'.

Creating a new doc should initialize a new temporary ID, so that the user can rename and edit this doc independently of other new/unsaved docs.

When a temporary doc is saved, it will (necessarily) get a new ID from the API of the persistence service (ie. github's gist api). When a doc is saved, we can remove all local references to the old temp-id. (But when a user has multiple tabs open, we may run into problems with 'ghost' docs.)

**Comment by mhuebert** [comment]
I've pushed a major update to how recent docs are tracked and how gist data flows through the app.

It is now possible to create as many new docs as you want, and they will all save locally independently.

It's currently deploying to dev.maria.cloud and it would be great if people could give it a try and see if any bugs are encountered!

**Comment by pedrorgirardi** [comment]
Thank you @mhuebert! I can't do today but will do tomorrow.

**Comment by pedrorgirardi** [comment]
The first time I open **Maria** it looks like this:

![screen shot 2017-09-18 at 14 14 39](https://user-images.githubusercontent.com/585191/30554754-fb1fff48-9c7b-11e7-8cf1-b09b43757cec.png)
_Each module has a friendly description_


If I open the **Example Gallery** document and go back to modules, now it looks like this:

![screen shot 2017-09-18 at 14 14 51](https://user-images.githubusercontent.com/585191/30554755-fb4b871c-9c7b-11e7-95f0-35793c73f009.png)
_Its friendly description is replaced by **gallery**_


The same happens after opening the intro document:
![screen shot 2017-09-18 at 14 15 01](https://user-images.githubusercontent.com/585191/30554756-fb62d160-9c7b-11e7-98ce-6130d2929f10.png)

It seems that the only doc that doesn't change its friendly description is the **Editor Quickstart** document:
![screen shot 2017-09-18 at 14 15 46](https://user-images.githubusercontent.com/585191/30554757-fb65bcae-9c7b-11e7-993d-117934e06678.png)

**Comment by mhuebert** [comment]
Thanks for catching this!

Those 'pretty' names were hard-coded by me. When you actually view the doc, they are replaced with the actual filename from the gist. 

(cc:  @daveliepmann - although we may still want to change how we load curriculum stuff, in the short term we should settle on what 'pretty' names we like, and then update the filenames in the gists - do you like "Example Gallery" and "Learn Clojure with Shapes"?)

**Comment by mhuebert** [comment]
OK, I have pushed a new version to https://dev.maria.cloud which reads curriculum files directly from GitHub. I also renamed the curriculum files to have friendly names, which match what I've hard-coded. So, in this new version:

- You can create as many local-storage-only docs as you want
- Save them to GitHub as gists
- See recently viewed docs
