### ISSUE TITLE
Github sign-in doens't work on Firefox

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#109]
Firefox Nightly version 57.0a1 on Linux

Clicking the "sign-in with Github" button does nothing. The console shows

"uncaught exception: Error: This browser is not supported or 3rd party cookies and data may be disabled."

**Comment by mhuebert** [comment]
Hmm, do you know what your 3rd party cookies/data settings are?

It looks like this error is coming directly from Firebase authentication, eg/ https://stackoverflow.com/questions/41736460/exception-this-browser-is-not-supported-or-3rd-party-cookies-and-data-may-be-di

By default, Firefox is set to have 3rd party cookies enabled. Using Firefox Nightly on mac, I can't replicate the error.

(The 3rd party cookies setting is hidden under Security > History > 'Use custom settings for history')

**Comment by plexus** [comment]
Yes, got it working now. I don't think I changed this setting before, it was set to "accept from visited". I changed it to "accept always" and now it works.

![2017-09-25-125314_498x109_scrot](https://user-images.githubusercontent.com/32212/30805187-9b8b3e4c-a1f0-11e7-86aa-9da7d64f9d83.png)

**Comment by mhuebert** [comment]
OK, great!

The [current default](https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences) for Firefox is to always accept third-party cookies, but awhile back they experimented in Nightly with [changing this default](https://blog.mozilla.org/netpolicy/2013/02/25/firefox-getting-smarter-about-third-party-cookies/) - it could be that's how your settings ended up that way.
