### ISSUE TITLE
(re) implement a modifier+click command to select form under mouse

### ISSUE THREAD

**Issue by mhuebert** [mhuebert/maria#113]
Introduce a mouse-based way to select valid forms in the editor.

**Comment by mhuebert** [comment]
Maybe try option instead of command, to avoid interfering with CodeMirror's multiple cursors.

- While holding option, update the selection as the user moves the mouse. 
- When the user clicks, 'set' the selection.
- If the user releases option without clicking, return the selection/cursor to its previous position. (So `option+mousemove` should create 'temporary' selections, similar to holding `M1` and adding `shift`.)

**Comment by jackrusher** [comment]
Aside: I had some hope that we would select by keyboard, move by mouse.

**Comment by mhuebert** [comment]
implemented, description: https://github.com/mhuebert/maria/issues/111#issuecomment-332047253

re: mouse manipulation: on the plus side, learners may be confronting so much new material at once that keyboard-only editing could be overwhelming, and direct mouse manipulation a help, both for actual editing / moving forms around, and learning to 'see' forms as something other than strings of text. on the minus side, habituation etc. we'll have to see how it works.
