### ISSUE TITLE
Copy/Pasting into other places does not preserve whitespace

### ISSUE THREAD

**Issue by daiyi** [mhuebert/maria#119]
This makes it difficult for me to move code between Maria and my usual text editors!

**Comment by mhuebert** [comment]
I think this is either a platform- or browser- specific thing, unsurprising since we have to try and appropriately tap into the system-level `copy` command. Which browser do you use?

**Comment by daiyi** [comment]
On my Linux box, whitespace seems to be preserved in Chrome but not Firefox!

**Comment by mhuebert** [comment]
OK, will look into it. thanks!

**Comment by mhuebert** [comment]
Confirmed, doesn't work for me in Firefox either.

**Comment by mhuebert** [comment]
I've pushed an update to https://dev.maria.cloud that should work (it fixes it for me in Firefox). Fix was using a `pre` element instead of a `div` for where we temporarily stash the content to be copied to the clipboard.
