### ISSUE TITLE
`what-is` is not a keyword

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#126]
### Issue:

![2017-10-06-105442_560x120_scrot](https://user-images.githubusercontent.com/32212/31270506-f66739c8-aa84-11e7-97cf-cce5564f0003.png)

I'm assuming this should say "function"?

### Environment:

  - Browser: Chrome, Firefox
  - Platform: Linux

### URL to a gist replicating the issue (if possible/relevant)  

https://dev.maria.cloud/gist/f07d7cb234cc0d94f75c3c975ca69da5

**Comment by jackrusher** [comment]
Ha!

**Comment by daveliepmann** [comment]
Look at @mhuebert go! 

![Usain bolt grinning as he runs fast](https://cdn-s3.si.com/images/cameron%20spencer.jpg)
