### ISSUE TITLE
[Firefox] Saving from local to gist results in empty screen

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#127]
### Issue:

- Sign in to github
- Create a new (local) sketch
- press save

You get the blue progress bar, the URI switches to `/gist/...`, and then you just get a blank grey background, and some errors in the console.

Copy/paste of the console: https://gist.github.com/b14a5a2267613adf85c7f89b0f58a31e

Screenshot of the same:

![2017-10-06-105933_1749x917_scrot](https://user-images.githubusercontent.com/32212/31270809-287a2b36-aa86-11e7-9ae6-f81d71e81b8f.png)

### Environment:

  - Browser: Firefox Nightly
  - Platform: Linux

**Comment by mhuebert** [comment]
I think this is fixed, would you mind trying in your browser on https://dev.maria.cloud?

**Comment by plexus** [comment]
Yes! it works now, thanks @mhuebert !
