### ISSUE TITLE
Argument order of `colorize` and `rotate` is "wrong"

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#128]
### Issue:

Typically clojure functions that work on a value/object take the value first. `colorize` and `rotate` do it the other way around.

I know it might be a bit late to do anything about this, but still wanted to point this out. If it were the other way around they would thread nicely, and be easier to use with things like `update` or `update-in`.

**Comment by jackrusher** [comment]
I think we'll have to leave the API (and considerable doc/examples) alone until after the teaching day tomorrow, but after that I'd be well pleased to have another look at the shapes API.

**Comment by jackrusher** [comment]
BTW, my rule of thumb is that likely invariants come before likely variants so as to make it easier to partially apply a given function. In the case of `colorize`, for example:

```
(map (partial colorize "blue") [... some shapes ...])
```

**Comment by plexus** [comment]
That's a valid argument. I agree to leave this as is for now.
