### ISSUE TITLE
Prevent apocalypse on evaluation of infinite sequence

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#13]
I'd like to use `repeat` for some of our examples, and it would be nice if we had an answer for what to show if the user evaluates an infinite sequence. 

e.g.  I'd like to encourage learners to evalute `(repeat (rectangle 20 20))` as part of understanding:

```
(map colorize
     ["red" "orange" "yellow" "green" "blue" "purple"]
     (repeat (rectangle 20 20)))
```

**Comment by mhuebert** [comment]
[Klipse](https://github.com/viebel/klipse)'s solution: https://github.com/viebel/klipse/blob/master/src/klipse/lang/clojure/guard.cljs

Of course when I first asked Jack about this, he referenced the theory: https://en.wikipedia.org/wiki/Halting_problem

**Comment by jackrusher** [comment]
Yeah, timeouts work fine for something like Maria but prediction is impossible in the general case. :)

**Comment by mhuebert** [comment]
Per our conversations - the specific case of large or infinite sequences can be handled most simply in 'format-value' by limiting the number of elements we 'take' from lazy seqs (& providing option to see more).
