### ISSUE TITLE
Ctrl-Shift-J (show JavaScript source) only shows up on next edit

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#130]
### Issue:

When using the "show javascript" functionality, it doesn't do anything *until* you make an edit. As soon as you e.g. press `space`, the JS source shows up.

### Environment:

  - Browser: Firefox, Chrome
  - Platform: Linux

**Comment by mhuebert** [comment]
Fixed, in dev.maria.cloud. 

Block views were getting updated on `eval!` but this command doesn't call `eval!` directly, it directly adds to the eval-log, so I moved the view update there.

Should be live on `dev` in a few minutes.

Thanks!
