### ISSUE TITLE
[nice to have] rgba / hsla functions

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#136]
There's an `rgb` and a `hsl` function, but no `rgba` or `hsla`. 

Use case: Venn diagrams :D 

https://dev.maria.cloud/gist/a3d6b00ea5ada528c4cdb3b0d8ce82d1

**Comment by daveliepmann** [comment]
`hsla` works for me in Chrome?

**Comment by plexus** [comment]
Dang seems I didn't save the right version of this... one sec.

**Comment by plexus** [comment]
better

![2017-10-06-121609_682x689_scrot](https://user-images.githubusercontent.com/32212/31273772-6309d3dc-aa90-11e7-8068-2427e8c3220b.png)

**Comment by daveliepmann** [comment]
We used to have these—Should be simple to add back in

**Comment by jackrusher** [comment]
I've just added them. Also, I've just done a pass with basic numeric parameter error checks in the shapes library.

**Comment by plexus** [comment]
Something I noticed here, how `position` works was surprising to me, e.g. the equivalent of

```
(circle 50)
```

is not

```
(position 0 0 (circle 50))
```

but


```
(position 50 50 (circle 50))
```

I'm guessing this has something to do with the weirdness of SVG coordinate systems.

**Comment by plexus** [comment]
Actually never minds, 50 is the radius, not the diameter. 🤦‍ and the position is the center 🤦‍ 

it makes sense now

**Comment by jackrusher** [comment]
`rgba` and `hsla` added, safety checks added. closing for now.
