### ISSUE TITLE
[minor] expanding source of `what-is` stuck on "Loading"

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#138]
- create a code block with contents

```
what-is
```

- evaluate
- press on the `f` to "view source"

=> gets stuck on "loading"

https://dev.maria.cloud/gist/48b8006dad55692e0898cf905343f6f7?eval=true

![2017-10-06-115609_1054x568_scrot](https://user-images.githubusercontent.com/32212/31273120-9bbab690-aa8d-11e7-8915-a9d60d316d9b.png)

Presumably because this is a macro? Similarly `in-ns` (which is a REPL special form) is not recognized.

**Comment by plexus** [comment]
Ok I'm done now... Sorry @mhuebert for the flood of issues!

**Comment by mhuebert** [comment]
The issue with `what-is` is because my parser doesn't support namespaced maps yet, but i used one in that namespace. have to fix that.

`in-ns` also throws a warning in lumo. as a special form it doesn't really have a value and isn't a var. not sure it should behave differently?

**Comment by plexus** [comment]
> in-ns also throws a warning in lumo. as a special form it doesn't really have a value and isn't a var. not sure it should behave differently?

Agreed, it doesn't really have a value. Still it could treat this as a special case and show something like `special form: in-ns`. (I don't feel very strongly about this, leaving it as is is also fine.)

**Comment by mhuebert** [comment]
Fixed `what-is` source lookup, added #140 to track adding namespaced map support.

will think about what to do with `in-ns`. it's a similar situation to macros, which currently show `:undeclared-var` warnings, but should really say 'can't take the value of a macro'.
