### ISSUE TITLE
[nice to have] Ctrl/Cmd-S on an already saved sketch brings up browser's "save page" dialog

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#139]
When a sketch is already saved and you press Ctrl-s / Cmd-s, it pops up the browser's "save page" dialog. For people like me who just constantly press Ctrl-s "to be sure", it would be better to ignore the second Ctrl-S.

Corrolary: [nice to have] autosave functionality

**Comment by mhuebert** [comment]
it's actually supposed to work this way, for some reason that event isn't being intercepted.

The doc constantly saves to local storage; i'm not sure at what frequency we'd want to be adding new revisions to the github gist?

**Comment by mhuebert** [comment]
Fixed
