### ISSUE TITLE
`rectangle` doesn't support arity of 1, despite docs claiming it does

### ISSUE THREAD

**Issue by daiyi** [mhuebert/maria#141]
![screenshot from 2017-10-07 11-10-26](https://user-images.githubusercontent.com/1589186/31306424-3d1596f0-ab50-11e7-9e46-1f6298140892.png)

**Comment by mhuebert** [comment]
Thanks!
Fixed. Not planning to push any changes until after today (don't want to risk breaking the build)

**Comment by daiyi** [comment]
thanks!!
