### ISSUE TITLE
`scale` doesn't expand drawable area

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#144]
### Issue:
Scaling a shape up correctly makes it bigger, but the drawable area does not expand to match. This makes the shape impossible to see. Consider:

`(scale 4 (circle 50))` shows only a corner of the circle

`(scale 10 (circle 50))` shows nothing because our viewport is the top left corner of a giant square containing a giant circle

### Environment:

  - Browser:
  - Platform (Mac/Windows/Linux):

**Comment by jackrusher** [comment]
Fixed in https://github.com/mhuebert/maria/commit/ace3aca1a4bba37b8bcdac87dd44d08d03a94065

**Comment by daveliepmann** [comment]
Closed because fixed in dev
