### ISSUE TITLE
[shapes] `beside` doesn't work on triangles

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#147]
### Issue:

Code

``` clojure
(beside
  (colorize "green" (triangle 50))
  (colorize "orange" (triangle 50)))
```

Expected:

![2017-10-08-115358_233x150_scrot](https://user-images.githubusercontent.com/32212/31315768-66db2d22-ac1f-11e7-9332-d36ffba2d785.png)

Actual:

![2017-10-08-115350_153x155_scrot](https://user-images.githubusercontent.com/32212/31315770-6e0ed63e-ac1f-11e7-8783-f816b156d087.png)

Demonstration

https://www.maria.cloud/gist/8615bc6aeae29b7e763af07ce5c8f327?eval=true

### Environment:

  - Browser: Firefox, Chrome
  - Platform: Linux

**Comment by mhuebert** [comment]
(typo in commit message, did not work on this issue)

**Comment by jackrusher** [comment]
Fixed in https://github.com/mhuebert/maria/commit/ace3aca1a4bba37b8bcdac87dd44d08d03a94065

**Comment by daveliepmann** [comment]
Closing because fixed in dev
