### ISSUE TITLE
Typing open paren does not replace selection

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#149]
- create code block
- select all code with C-a
- press `(`

Expected: code block has been replaced with `()`

Actual: `()` has been inserted at the end

### Environment:

  - Browser: Firefox, Chrome
  - Platform: Linux

**Comment by mhuebert** [comment]
Thanks for the issue. Should ignore the 'open bracket' command when there is a selection.

**Comment by daveliepmann** [comment]
My preferred behavior for myself, which I submit merely as a possibility for Maria, is that when I have an expression selected and I type `(`, the parens wrap the expression. So, with the selection marked by `|` and my cursor before the `a`:

`|abc|` -> `(|abc)`

**Comment by mhuebert** [comment]
Select+( for wrap, that's interesting. I'd like to try this after getting
keybindings sorted.
