### ISSUE TITLE
URL structure for intro and modules

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#15]
Before we release on the web, we should have a URL structure in place that auto-loads our curriculum. We'd then have a separate path for a scratchpad that starts empty and stores user input in localstorage.

Perhaps
 - `/` --> *docs/quick_intro.cljs*
 - `/modules/<n>` --> *docs/module_<n>.cljs* (where *n* is a name or number?)
 - ???

**Comment by mhuebert** [comment]
Structure looks good. I'm thinking we'll want to load lesson content over the wire from Github (vs. bundling everything along with the source, or stuffing clojure files into `resources/public`)... so the only requirement is that we can derive a filepath from the url. And maybe we should 'namespace' the modules from the start, so we can add specialized topics later.. 

```
/modules/intro/1             >    /modules/intro_1.cljs
/modules/linear-algebra/1    >    /modules/linear_algebra_1.cljs
```

For local storage - related to #14, I'm thinking we could allow users to mess with whatever file happens to be loaded into the REPL, saving to local storage along the way, as long as there is a 'reload' button to reset to the original content. it would be frustrating to be experimenting while following along with a tutorial and have a browser crash lose your progress.

**Comment by mhuebert** [comment]
Closing this for now, as we have a basic structure in place (see https://github.com/mhuebert/maria/issues/39#issuecomment-314389759)
