### ISSUE TITLE
"Revert" on long files causes several seconds of hang

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#156]
### Issue:
On both the Gallery and Learn Clojure with Shapes, clicking "Revert" causes several seconds of hang.

### Environment:

  - Browser: Chrome, Version 61.0.3163.100 (Official Build) (64-bit)
  - Platform (Mac/Windows/Linux): Mac

**Comment by mhuebert** [comment]
Yes, some recent change(s) have slowed things down considerably overall.
I'll try and track this down.

**Comment by mhuebert** [comment]
Turns out that generating the 'share' links, which requires some parsing, was the main culprit 🙄. Also added a necessary `should-update` method to the prose editor. 

Should be much faster now. Pushed to dev.maria.cloud.
