### ISSUE TITLE
update `source` command to work with shadow-cljs output

### ISSUE THREAD

**Issue by mhuebert** [mhuebert/maria#157]
Previous `source` command had dependency on cljs-live output structure. Must update to work with shadow-cljs.

**Comment by thheller** [comment]
`(shadow.cljs.bootstrap.env/get-ns-info 'some.ns)` should contain a `:source-name` which should be used together the bootstrap path passed in earlier. I did not create a helper function for this yet.

**Comment by mhuebert** [comment]
Pushed to dev.

![image](https://user-images.githubusercontent.com/165223/31796462-eec3fed6-b529-11e7-8c99-5cbfa33e5000.png)
