### ISSUE TITLE
Info: Revised Keyboard Bindings

### ISSUE THREAD

**Issue by mhuebert** [mhuebert/maria#158]
I have been playing with the following configuration, and just pushed to dev for review. I have tested on Mac (Chrome) and Windows (Firefox, Edge).

*LEGEND*

`M1` is `Command` on a mac, `Control` on a PC.
`M2` is `Option` / `Alt`

**Eval**

`Shift Enter` to eval the current top-level form. 

`M1 Enter` to eval the current selection. 

**Selections** 

`M1` temporarily selects the form near the cursor.

`M1` plus   `↑`, `←`, `→` to expand selections.

`M1 ↓` to contract selection (based on previous expansion history). 

`M1` plus mouse movement will select forms on hover, allowing for drag and drop.

**Edits** 

`M1` plus `C` or `V` to copy and paste. 

`M1 Shift V` is now paste-replace (*not working on windows yet).

`M1 Shift` plus `→`, `←` for slurp/barf.

`M1 S` for unwrap. Or, delete the opening bracket of a pair to remove them both. Backspace does not remove `"`'s if it would unbalance the string.

**Movement**

`M2` plus `←` or `→` jumps the cursor to the far edge of the prev/next form.

`M2` plus  `↑` or `↓` jumps cursor to top/bottom of current block.

`M2 Shift` plus  `←` or `→` jumps cursor to start/end of current line.

`M2 Shift` plus  `↑` or `↓` jumps cursor to prev/next block.

**A Game!**

I think a small game of some kind would be a nice way to present and learn these key bindings. 

----

As an aside,

Earlier today I was debugging keybindings in a Windows 10 virtual machine, trying to bind `M1 shift )` and `M1 shift (` to slurp/barf respectively. I found that`keyup` events would fire, but `keydown` events for `M1 shift )` would not, no matter how I tried to bind them. Turns out to be a Windows thing: binding `Ctrl Shift 0` is [simply not possible](https://support.microsoft.com/en-us/help/967893/input-method-editor-keyboard-shortcut-ctrl-shift-0-switches-the-input) without the user digging into their OS settings. 

Adding to the intrigue, `0` sits below different characters depending on the [language of your keyboard](https://medium.com/@mwichary/international-apple-keyboards-layouts-93437d7f9273): 

- `)` on English, French-Canadian, Dutch, Russian, Korean, Chinese, Thai, Arabic
- `=` on Croatian, Turkish (Q), Spanish, Portuguese, Danish, Norwegian, Swedish, Italian, German, Swiss
- `§` on Hungarian, `:` on Turkish (F), and on French and Czech, `0` is shifted character, behind `à` and `é` respectively.

...which means one can't bind `Ctrl Shift =` or -`)` or -`:` reliably.

One can reasonably conclude that the only _true_ path to a smooth, predictable keybinding experience is to make our own operating system. And hardware.

**Comment by jackrusher** [comment]
Really enjoying the selection + slurp/barf keybinds! This is feeling much more natural.

> One can reasonably conclude that the only true path to a smooth, predictable keybinding experience is to make our own operating system. And hardware.

In the words of the Flowerpot from Hitchhiker's Guide:
![](https://media1.tenor.com/images/96b5139e06505e71aec5a5cacbb6bec3/tenor.gif?itemid=6224065)

**Comment by mhuebert** [comment]
> This is feeling much more natural.

great!

I think getting rid of the modifier that auto-temporarily-selects the top-level form is going to be a good improvement overall.  

----

for future reference:

![us](https://user-images.githubusercontent.com/165223/31767744-ac37e512-b4cc-11e7-9cf0-3f0ac18e71ec.png)

![german](https://user-images.githubusercontent.com/165223/31767773-ba3ecde2-b4cc-11e7-8b96-fc32340db9bf.png)

**Comment by pedrorgirardi** [comment]
It does feel good :)

Maria is only getting better and better! It makes me want to have such environment for "normal development" in Clojure & ClojureScript. 😅
