### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by mhuebert** [mhuebert/maria#162]
I've just pushed an update to `dev` which should significantly speed up typing inside a large documents. Previously, there was some work being done on each keystroke to 'stringify' the entire doc for comparison purposes, which would grow along with the size of the doc (mainly the size of code blocks). This was particularly problematic because the first doc a typical user will see is the very large intro! :-)

Now, the string for each block is effectively 'cached' on change. On the intro doc, this led to a ~100x speedup in my development build. I also added a small debounce to the autocomplete, which speeds up typing a tiny bit and has a large effect when doing something like holding the delete key down.

To get a feel for the change, you can try making changes to the last block ("Fernseheturm") in the `dev` vs `www` builds:
https://dev.maria.cloud/gallery
https://www.maria.cloud/gallery

The change was not that extensive, but because it cuts across multiple important concerns (parsing, persistence) we should test this rather extensively in dev (creating / editing / reloading docs) before pushing to `www`. 

I also learned that Google Closure `:simple` optimizations can have a really big impact on performance. Parsing the entire 11k LOC `cljs.core` file on my machine (using `lark/tree`) takes ~4 seconds in a dev build, but only ~0.5 seconds with `:optimizations :simple`. If total parse time is on the order of 0.05ms per line of code, unless a user puts more than 100 lines of code in a single top-level form, our parsing step should add less than 5ms per keystroke. But I am on a fast mac so I should really try using Maria on a chromebook from time to time.

**Comment by jackrusher** [comment]
Noticeably faster.

**Comment by mhuebert** [comment]
Implementation note, discovered with @thheller that the primary reason things were so slow in the `dev` build was not the lack of Closure :simple optimizations (that makes a difference, but only on the order of ~20%), but rather a consequence of loading scripts asynchronously and then `eval`ing them (vs. using `script` tags). It turns out that V8 does not optimize the code that is passed to `js/eval`, and that's why it was so horrendously slow. (Firefox does optimize eval'd code so this was not an issue there.) 

(It has been fixed so in future versions things will run faster in dev)
