### ISSUE TITLE
Iframe violates Chrome Geolocation Policy

### ISSUE THREAD

**Issue by theronic** [mhuebert/maria#172]
### Issue:

Running `(defcell location (geo-location))` in [data-flow sample](https://dev.maria.cloud/data-flow 
) throws "Geolocation access has been blocked because of a Feature Policy applied to the current document. See https://goo.gl/EuHzyv for more details."

### Solution as per [Chromium notice](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes):

```
<iframe src="..." allow="geolocation">
```

### Environment:

  - Browser: Chrome 64.0.3282.167
  - Platform (Mac/Windows/Linux): Mac

### URL to a gist replicating the issue (if possible/relevant)

**Comment by mhuebert** [comment]
Good catch, and thanks for looking up the solution! 

Pushes to `master` deploy automatically to dev.maria.cloud, so this should be testable there in 3-4 minutes.
