### ISSUE TITLE
defn misplaced argument(s)

### ISSUE THREAD

**Issue by davidsavoie1** [mhuebert/maria#177]
### Issue:
At the `defn` explanation diagram, argument(s) are not shown at the right place. They point at the second `color` word, which is part of the actual expression.

Should have been like
```clojure
(position 195 25 (rotate 60 (colorize "grey" (triangle 10))))
(position 160 20 (text "argument(s)"))
```

### Environment:

  - Browser: Chrome
  - Platform (Mac/Windows/Linux): Windows

### URL to a gist replicating the issue (if possible/relevant)  
![image](https://user-images.githubusercontent.com/25533167/36764848-86376d64-1bfc-11e8-9ba2-fb6a694ba186.png)

**Comment by daveliepmann** [comment]
You're absolutely right. We switched fonts a while back and it broke the alignment of our diagram. 

The reason we haven't fixed it yet is that we plan to replace the diagram by an image anyway, and I just haven't gotten around to making that image. We were excited by the idea of explaining the tool using the tool itself...but it just didn't work. It confused a majority of the target audience of beginners.

**Comment by daveliepmann** [comment]
I'll note here a few more troubling aspects I see. 

 - typeface vastly differs from maria.cloud style
 - no syntax highlighting
 - example's use of vector for the expression unnecessarily confuses things with the arglist

**Comment by daveliepmann** [comment]
Revised dogfooded diagram:

<img width="1372" alt="screen shot 2018-02-28 at 8 57 58 am" src="https://user-images.githubusercontent.com/974443/36776534-72415b98-1c66-11e8-8990-50079416d2f8.png">

**Comment by daveliepmann** [comment]
OK, the revised diagram using a dogfood approach is in place in both `dev` and `www`. We're using an image-based diagram for the next iteration of the curriculum and frankly it's a lot better, so stay tuned for that as well.
