### ISSUE TITLE
Scaling up doesn't work on rectangles/squares

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#182]
### Issue:
Rectangles (including squares) cannot be embiggened with `scale`. For shapes created with `rectangle` or `square`, scaling amounts >1 are treated as 1. Scaling up works on circles (though the viewport remains constant, which is a separate problem.)

### Environment:
FF / Mac High Sierra

**Comment by jackrusher** [comment]
Fixed in https://github.com/mhuebert/maria/commit/ace3aca1a4bba37b8bcdac87dd44d08d03a94065
