### ISSUE TITLE
Evaluating special forms (e.g. `let` or `fn`) causes error

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#184]
### Issue:
I'd like to evaluate clojure.core macros, e.g. `fn` or `let`, directly in the Maria REPL. However, this causes an `:undeclared-var` error:

<img width="1680" alt="screen shot 2018-03-02 at 9 43 20 am" src="https://user-images.githubusercontent.com/974443/36890455-34f01f4c-1dfe-11e8-8ae6-a1a007e53c8f.png">

Is this feasible without major effort? It's not a pedagogical necessity, merely an inconsistency.

(_Usage_ of these macros—e.g. `(fn [] ...)` or `(what-is let)`—works fine.)

Probably related to #151.

**Comment by theronic** [comment]
Nit: `fn` and `let` are special forms in Clojure, not macros. But I see Maria shows the same error for macros (like for) or special forms, even when fully namespaced, e.g. `clojure.core/fn`.

**Comment by daveliepmann** [comment]
Nice catch. Describing these special forms as macros is my oversight, but we seem to have a bug in `friendly.kinds` that doesn't catch special forms. Investigating.

**Comment by daveliepmann** [comment]
My mistake—the faulty magic is happening in the editor, specifically `maria.repl-specials/what-is`.

**Comment by daveliepmann** [comment]
Once eac6f77 finishes its build, we should see correct results from `(what-is fn)` and `(what-is let)` in `dev`.
