### ISSUE TITLE
Broken link in wiki

### ISSUE THREAD

**Issue by eggsyntax** [mhuebert/maria#186]
### Issue:

Hey folks, just wanted to let y'all know you've got a broken link on the wiki home screen (https://github.com/mhuebert/maria/wiki). The link to "Error Handling page" is broken; when I hover over it it shows `https://github.com/https://github.com/mhuebert/maria/wiki/Error-Handling`. No rush on my account, I can get to that page another way; I just wanted to make you aware.

Thanks for your work on this!

**Comment by daveliepmann** [comment]
Thanks! Fixed.
