### ISSUE TITLE
colors-named hasn't been defined

### ISSUE THREAD

**Issue by alpyne** [mhuebert/maria#190]
### Issue:

Evaluating `(colors-named "light")`in the intro document results in the following error:

> `colors-named` hasn't been defined! Perhaps there is a misspelling, or this expression depends on a name that has not yet been evaluated?
(:undeclared-var)
undefined is not an object (evaluating 'maria.user.colors_named.call')

### Environment:

  - Browser: Safari 11.0.3
  - Platform (Mac/Windows/Linux): MacOS 10.12.6
  

### URL to a gist replicating the issue (if possible/relevant)  

https://www.maria.cloud/intro

**Comment by daveliepmann** [comment]
Thanks for reporting this. It seems this slipped through as part of the v2 curriculum despite relying on functionality that is still `dev`-only right now. We should be making a production build in the next few days, which should resolve it. Until then I'll keep this ticket open.
