### ISSUE TITLE
this.mseq.cljs$core$ISeq$_first$arity$1(null).cljs$core$IMapEntry$_key$arity$1 is not a function.

### ISSUE THREAD

**Issue by amonks** [mhuebert/maria#195]
### Issue:

I tried to evaluate the form beginning with `(defcell a-color` on https://dev.maria.cloud/animation-quickstart, but I got the following error:

```
(defcell a-color (interval 250 #(rand-nth (keys color-names))))
this.mseq.cljs$core$ISeq$_first$arity$1(null).cljs$core$IMapEntry$_key$arity$1 is not a function. (In 'this.mseq.cljs$core$ISeq$_first$arity$1(null).cljs$core$IMapEntry$_key$arity$1(null)', 'this.mseq.cljs$core$ISeq$_first$arity$1(null).cljs$core$IMapEntry$_key$arity$1' is undefined)
```

### Environment:

  - Browser: Safari 10.12.6
  - Platform (Mac/Windows/Linux): MacOS

**Comment by daveliepmann** [comment]
Thanks for reporting this! :)

**Comment by daveliepmann** [comment]
For future reference, this was fixed by switching `(keys color-names)` to `(map first color-names)`. If your copy of the Animation Quickstart still has the old code, click "Revert" at the top.
