### ISSUE TITLE
Broken "Pedagogy" link

### ISSUE THREAD

**Issue by amonks** [mhuebert/maria#196]
### Issue:

On the page https://www.maria.cloud, the link with the text "Pedagogy" points to [this url](https://github.com/mhuebert/maria/blob/master/curriculum/pedagogy.md) which 404s.

a5de9c1b8721b3fb1e1396197b9f8616021d8d10 removed that page from the master branch and changed the link to point to the wiki. The page and link still exist in the release branch.

### Environment:

  - Browser: Safari 10.12.6
  - Platform (Mac/Windows/Linux): MacOS

**Comment by daveliepmann** [comment]
Thanks for reporting this. That commit was a little early but we just pushed a release and this should be fixed.
