### ISSUE TITLE
Automatic indentation follows position of inline comment

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#197]
### Issue:
In the [intro](https://www.maria.cloud/intro), we have this commented `let` block that draws a mountain range by positioning triangles:

```clojure
(let [t (triangle 100)] ;; <-- this vector holds our name/value pair
  ;; now we write an expression using that name:
  (layer t
         (position 50 0 t)
         (position 88 0 t)
         (position 113 0 t)
         (position 185 0 t)
         (position 195 0 t)
         (position 238 0 t)))
```

If I try to add a second space between the `50` and `0` in the first `position` (to line up all the zeros vertically), then the entire form indents. Normally this is desired automatic behavior. However, the comments are detected as statements to match indentation with, so we get:

```clojure
(let [t (triangle 100)] ;; <-- this vector holds our name/value pair
                        ;; now we write an expression using that name:
                        (layer t
                               (position 50  0 t)
                               (position 88 0 t)
                               (position 113 0 t)
                               (position 185 0 t)
                               (position 195 0 t)
                               (position 238 0 t)))
```

I expected something closer to:

```clojure
(let [t (triangle 100)] ;; <-- this vector holds our name/value pair
  ;; now we write an expression using that name:
  (layer t
         (position 50  0 t)
         (position 88 0 t)
         (position 113 0 t)
         (position 185 0 t)
         (position 195 0 t)
         (position 238 0 t)))
```

Should we perhaps ignore comments as regards automatic indentation? (Or, we could ignore only single-semicolon comments for automatic indentation.)

### Environment:

  - Browser: firefox 59.0.1 (64-bit)
  - Platform (Mac/Windows/Linux): Mac

**Comment by mhuebert** [comment]
Good catch... fixed in b665453, deploying now
