### ISSUE TITLE
Ctrl/Cmd-Enter on prefixed forms does not include prefixes

### ISSUE THREAD

**Issue by yuhan0** [mhuebert/maria#205]
### Issue:

Literals for hash sets, anonymous functions, quoted exprs etc. are evaluated _without_ their preceding prefix chars when using Ctrl/Cmd-Enter at the end of the expression. 

Eg. the following are all valid literals but produce syntax errors when evaluated:
```clojure
#{1 2 3}

#(* 2 %)

'(a b c)

#_(ignore me)
```

A current workaround seems to be navigating to the beginning of the expression before the prefix chars, then evaluating the form, however they should be treated as a single logical unit.

### Environment:

  - Browser: Firefox
  - Platform (Mac/Windows/Linux): Mac

**Comment by daveliepmann** [comment]
Replicated [here](https://www.maria.cloud/gist/1e5735c375d521291ad2c42cb68b0d11). Thanks for reporting this regression!

**Comment by mhuebert** [comment]
Thanks for the report & replication!
I've just pushed a fix, it's live now on maria.cloud.
