### ISSUE TITLE
formatting of higher order functions

### ISSUE THREAD

**Issue by yuhan0** [mhuebert/maria#207]
### Issue:

Evaluating higher order functions doesn't seem to be supported well, resulting in an unfriendly error message. 

With the standard shapes library, a beginner might try to write:
```clojure
(let [yellowize (partial colorize "yellow")]
  (yellowize (square 100)))
```
Ctrl-enter on the form `(partial colorize "yellow")` returns the following :
>c
function(a,b,c,n){switch(arguments.length){case 0:return d.call(this);case 1:return e.call(this,a);case 2:return f.call(this,a,b);case 3:return g.call(this,a,b,c);default:var k=null;if(3<arguments.length){k=0;for(var l=Array(arguments.length-3);k<l.length;)l[k]=arguments[k+3],++k;k=new cljs.core.IndexedSeq(l,0,null)}return h.cljs$core$IFn$_invoke$arity$variadic(a,
b,c,k)}throw Error("Invalid arity: "+arguments.length);}

It's not clear what the "correct" output should be, perhaps just "Anonymous function" (with its expected arities, if that's introspectable)

### Environment:

  - Browser: Firefox 
  - Platform (Mac/Windows/Linux): Mac 

### URL to a gist replicating the issue 

Several more examples in the gist:
https://www.maria.cloud/gist/9670bc9c82f10c7dc6b563c84c6b62a3

**Comment by mhuebert** [comment]
I'm not aware of any existing way to get that kind of metadata on higher-order functions, but I agree this would be really nice thing to visualize better. eg. see the original function + what "slots" have been filled.

**Comment by daveliepmann** [comment]
Excellent point raised. Thanks.

>It's not clear what the "correct" output should be, perhaps just "Anonymous function" (with its expected arities, if that's introspectable)

The precedent set by how we display `(fn  [x] (inc x))` and `(fn ihaveaname [x] (inc x))` (with a function symbol expanding to their definition) suggests to me that `(partial colorize "yellow")` should perhaps evaluate to simply that same function symbol expanding to the definition, `(partial colorize "yellow")`.

Though I agree that surfacing more info about fns in that space is intriguing on its own merit :)

**Comment by mhuebert** [comment]
> perhaps evaluate to simply that same function symbol expanding to the definition, (partial colorize "yellow") 

attempting something along those lines, getting mixed results:
![image](https://user-images.githubusercontent.com/165223/57193929-e1e54580-6f40-11e9-8a3e-b21ab095ce99.png)

![image](https://user-images.githubusercontent.com/165223/57193922-d3972980-6f40-11e9-867b-e54d6dbd23f2.png)

**Comment by mhuebert** [comment]
Closing but still interested, marked as 'research required'
