### ISSUE TITLE
`implements?` hasn't been defined!

### ISSUE THREAD

**Issue by socksy** [mhuebert/maria#208]
https://www.maria.cloud/gist/0e2f9b0a735cb6762ef016fcdb798d86?eval=true was working fine last week, now the functions from `levain-ratio` onwards fail with "`Implements?` hasn't been defined!". I am not using `Implements?`, so this is confusing. True on both chrome and firefox on linux.

**Comment by yuhan0** [comment]
I'm encountering this regression too, looks like a map destructuring bug. 
Here's a minimal failure case:
```clojure
(let [{a :a} {:a 1}])

(let [{:keys [a]} {:a 1}])
```

**Comment by mhuebert** [comment]
thanks for this report!
I can reproduce it further to usage of `implements?` within the test clause of an `if` expression:
https://www.maria.cloud/gist/9902c3abb9988e06252e745ff5cebe29?eval=true

**Comment by mhuebert** [comment]
I've reverted our ClojureScript version to `1.10.439` which fixes the issue for me.

I have pushed the `1.10.520` version to our dev build for further testing/reporting. https://dev.maria.cloud/gist/9902c3abb9988e06252e745ff5cebe29?eval=true

**Comment by mhuebert** [comment]
Thanks again @socksy & @yuhan0 for this thread. It led to a discovery that we weren't handling warnings properly during compilation, and also an incorrect error message. Big thanks to @mfikes for his help tracking this all down. We're back on cljs `1.10.520` now, please let us know if you find anything else amiss.
