### ISSUE TITLE
Autoformat whitespace

### ISSUE THREAD

**Issue by mhuebert** [mhuebert/maria#21]
Maria should support auto-formatting code (indentation, alignment.).

**Comment by jackrusher** [comment]
Some variation on [aggressive-indent-mode](https://github.com/Malabarba/aggressive-indent-mode) would be really nice.

**Comment by jackrusher** [comment]
Shorter term, it would be nice if at least copy/pasted code were formatted. (Currently pasted code gets put on one long line.)
