### ISSUE TITLE
Background Reading Wiki Page - URL Update

### ISSUE THREAD

**Issue by mhuisking** [mhuebert/maria#215]
### Issue: 
Hi!  Found a broken link to the SICP Picture Language in the "Background Reading" page (https://github.com/mhuebert/maria/wiki/Background-reading)  MIT Press has updated the URL to: https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-15.html#%_sec_2.2.4

Thanks for your work on this project.
Mick

**Comment by daveliepmann** [comment]
I appreciate you reporting this. I updated the link. Thanks!
