### ISSUE TITLE
Evaluation is broken on maria.cloud

### ISSUE THREAD

**Issue by alesguzik** [mhuebert/maria#216]
### Issue:

If you go to https://www.maria.cloud/intro , put your cursor at `(circle 25)` or any other form and press Ctrl+Enter, you'll get:
* `Compile error: we were unable to turn this code into JavaScript. 😰`
* `cljs.core.find_macros_ns(...) is null` (firefox) or `Cannot read property 'findInternedVar' of null
` (chrome)
* `No such namespace: maria.friendly.kinds, could not locate maria/friendly/kinds.cljs, maria/friendly/kinds.cljc, or JavaScript source providing "maria.friendly.kinds"
(:undeclared-ns)`

There are no errors in the console when the page loads, but in the network tab, while most requests return 200, a request to https://user.maria.cloud/js/compiled/bootstrap/ana/87115140.maria.views.hoc.transit.json returns `404`.

### Environment:

  - Browser: Firefox, Chrome
  - Platform (Mac/Windows/Linux): Linux

**Comment by alesguzik** [comment]
Works fine now, not really sure what was the problem.

**Comment by daveliepmann** [comment]
We appreciate you reporting the hiccup (possibly the network dropped a packet?), even though it resolved itself.
