### ISSUE TITLE
[idea] expose a repl page

### ISSUE THREAD

**Issue by stopachka** [mhuebert/maria#229]
Hey team, I _love_ the work you've done on this. Wanted to share an idea with you: 

It may make sense to expose a "repl" page on maria. This one would be without any tutorial -- just a way for someone to play with clojure. 

This may be outside of the scope of what ya'll are trying to do, but think it could be valuable for the community. The existing solutions aren't as good as what you have. 

If it is outside of your scope, can fork this and make a quick site, but wanted to share with you first.

**Comment by jackrusher** [comment]
Hi! Isn't every page a REPL page? You can go to landing page and press the "new" option in the upper left corner to start a new notebook at any time. :) Does that do what you need?

**Comment by stopachka** [comment]
hmm good point this does work pretty well! okay maybe on light idea: if there was a quick maria.cloud/n url, which automatically generated and got you into a new page (hence no need to visit the page and click the button) 

(though indeed that is a pretty light change)

**Comment by daveliepmann** [comment]
I agree, some sort of `/new` path would be handy. I have a vague memory that we may have had this in the past?

**Comment by mhuebert** [comment]
@stopachka a bit late to the party but I've added a `/new` route that does this, it's currently deployed to our dev site `dev.maria.cloud` for testing.

@daveliepmann that does ring a bell, may have had something like this in an earlier version..

**Comment by stopachka** [comment]
That’s aweesome!
