### ISSUE TITLE
Display commands when modifier keys are pressed

### ISSUE THREAD

**Issue by mhuebert** [mhuebert/maria#23]
There is currently no way to discover or modify keyboard shortcuts.

**Comment by jackrusher** [comment]
I'm hoping for something like [which-key](https://github.com/justbur/emacs-which-key), with priority given to "discover" rather than "modify".

**Comment by mhuebert** [comment]
Good idea. 

If we `def` all the command functions (as opposed to anonymous functions in a keymap) then we could pull in docstrings from the environment and reveal them (somehow) in the exploration interface..

```
(defn slurp 
    "Expand the current expression to include the next form.
     (inc |) 1 => (inc |1)"
  [cm {:keys [cursor-loc}]
  ...implementation...)
```

**Comment by mhuebert** [comment]
Implementation note (via Jack) - keymap patterns may be specified as strings (`"cmd-enter"`) but normalized to a map of the form `{<set>, <command>}`:

```clj
{#{:mod :enter}         {:command :eval/selection}
 #{:mod :shift :enter}  {:command :eval/top-level}}
```

This will support the 'keymap-explore' interface by making it simple to filter based on any number of modifier keys being pressed.

**Comment by jackrusher** [comment]
N.B. We will want to add a short intro to the `which-key`-like functionality at the head of the level 0/quick intro.

**Comment by mhuebert** [comment]
Added `which-key` ui in 7db0e817f3dadd6f3a486024276a191fc1dd2167.
