### ISSUE TITLE
Evaluation turns editor into a blank page

### ISSUE THREAD

**Issue by itaydre** [mhuebert/maria#256]
### Issue: Evaluation turns editor into a blank page.
It seems like this expression (+ (first "Hello World") (rest "Hello World")) caused it. I'm not sure whether it's a bug or something I do by mistake...

### Environment: Mac

  - Browser: Chrome 104

https://user-images.githubusercontent.com/29481587/187700388-c653f9d8-1a6a-4695-a930-8e30b9e02c1b.mov

  - Platform (Mac/Windows/Linux):

**Comment by mhuebert** [comment]
thanks @itaydre for the report. I'm closing as this works correction in Maria 2: https://2.maria.cloud/gist/470125f8f3ad78506a779c4de224979c
