### ISSUE TITLE
Typing [ on iOS keyboard is replaced with {

### ISSUE THREAD

**Issue by danielcompton** [mhuebert/maria#259]
### Issue:

I tried writing a function on the iOS keyboard. Whenever I typed `[`, `{` was printed.

### Environment:

  - Browser: Safari
  - Platform: iOS 16
  

### URL to a gist replicating the issue (if possible/relevant)  

https://user-images.githubusercontent.com/811954/209414229-11b418f7-e6ee-4b6b-a697-92833df1c17e.MP4

**Comment by mhuebert** [comment]
@danielcompton thanks! Can you verify that this works as expected at 2.maria.cloud? keyboard shortcut reliability _should_ see a big improvement in the new version (haven’t launched it at maria.cloud yet because I still have to implement the command palette, persistence etc with the new codebase)

**Comment by danielcompton** [comment]
Yep working perfectly there. Thanks!
