### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by chrisjj** [mhuebert/maria#263]
...

**Comment by paul-marechal** [comment]
Regarding the issue you originally reported, it seems like you were missing the following definition:

```clojure
(def rainbow
  ["red" "orange" "yellow" "green" "blue" "indigo" "violet"])
```

**Comment by chrisjj** [comment]
Yes! I deleted the issue because I discovered just that.

Well Done for such a great resource!

**Comment by paul-marechal** [comment]
The issue is still up and opened though, you may want to look into closing it now.

**Comment by chrisjj** [comment]
Thanks. Done.
