### ISSUE TITLE
Example gist for cells is broken `self` hasn't been defined.

### ISSUE THREAD

**Issue by benjamin-asdf** [mhuebert/maria#272]
### Issue:

https://www.maria.cloud/gist/1a561967af1238fa5fd391c7925d364b

evaling the first 2 blocks leads to an error. 
"Self" is not defined

### Environment:

  - Browser: tried with google chrome 
  - Platform (Mac/Windows/Linux): doesn't matter :P 
  

### URL to a gist replicating the issue (if possible/relevant)  

https://www.maria.cloud/gist/1a561967af1238fa5fd391c7925d364b

**Comment by daveliepmann** [comment]
Thanks!

In 2.maria we get:

>could not resolve symbol: with-view

**Comment by mhuebert** [comment]
I've added `with-view` support to 2.maria.cloud and updated the gist a bit so that everything works: https://2.maria.cloud/gist/1a561967af1238fa5fd391c7925d364b
