### ISSUE TITLE
Pressing Esc changes focus or state but that is not obvious and causes problems

### ISSUE THREAD

**Issue by pangloss** [mhuebert/maria#273]
### Issue:

As an Emacs/Vim user I have a bad habit of hitting Esc after I finish typing something. That has no (or minimal?) visible effect in the UI. Worse, the cursor is still flashing in the same place after Esc is pressed.  But after pressing Esc, pressing another key replaces the entire cell with whatever character you pressed and then unfocusses. It's annoying that the cell has disappeared, but it's much worse that because focus is lost, you can't immediately undo.

If the cell state or mode is such that pressing a key will replace the cell, that should be much more strongly visible. I think Jupyter changes the cell color.

### Environment:

  - Browser: FF
  - Platform Mac

**Comment by mhuebert** [comment]
Good report! Thank you.

Escape currently selects the entire cell; I agree it would be good to (a) show an obvious border and (b) blur the code cell so the cursor disappears

**Comment by mhuebert** [comment]
Code cells should now show a border when they are selected, and they are blurred so the cursor is not visible. (just pushed; should be live in a couple minutes.)

![image](https://github.com/mhuebert/maria/assets/165223/c3ef3e4d-5539-48da-ac5e-a362dd8159ee)
