### ISSUE TITLE
No way to revert to original gist

### ISSUE THREAD

**Issue by pangloss** [mhuebert/maria#274]
### Issue:

I'm trying out an Emmy sample backed by a gist. I was messing with it and messed it up. Unfortunately now I can't use it and there is no apparent way to revert my version to the original gist.

### Environment:

  - Browser: FF
  - Platform Mac
  

### URL to a gist replicating the issue (if possible/relevant)  

https://2.maria.cloud/gist/d3c76ee5e9eaf6b3367949f43873e8b2

**Comment by mhuebert** [comment]
Thanks for the report! Do you see a Revert option in the file menu or command bar? Maybe confusing for it to not be in the title drop-down...

**Comment by mhuebert** [comment]
I've moved all the related commands under the title dropdown, should be clearer:
![image](https://github.com/mhuebert/maria/assets/165223/1b1d6943-c3f4-442c-85c7-9ba4883d2c2c)
