### ISSUE TITLE
Save to gist

### ISSUE THREAD

**Issue by jackrusher** [mhuebert/maria#29]
If the user is logged in to Github it would be great if they could save the current "buffer" to a gist. If the code was loaded from a gist, I would expect to save back to that gist (like "save" functionality in a local editor); otherwise, it would just generate a new gist with the contents of the current editor.

**Comment by mhuebert** [comment]
Current blocking issue is security. Auth tokens that we use to sign users in must not be readable by third-party code that users load into the environment (eg. from gists).

Possible approach: put the whole live-eval environment into a sandboxed iframe? (see https://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/)

**Comment by mhuebert** [comment]
Finished (via several recent commits).
