### ISSUE TITLE
Rectangle should accept one argument

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#36]
`(rectangle 50)` should make a square

**Comment by jackrusher** [comment]
See: `(square 50)`

**Comment by daveliepmann** [comment]
:/

**Comment by jackrusher** [comment]
Having a hard time extracting much meaning from your `:/`, Liepmann. You want both, or...?

**Comment by daveliepmann** [comment]
I think both would be nice. Is the argument against that we don't want a function that is `doc`'d early in lesson 0 to be multi-arity?

**Comment by jackrusher** [comment]
I don't like introducing multiarity and overloading terminology. "The `square` function makes a square" seems clearer to me. (But I'm not overly attached to it, just a feeling.)

**Comment by daveliepmann** [comment]
>I don't like introducing multiarity and overloading terminology.

I hadn't thought of this when I expressed disappointment with the lack of multi-arity `rectangle`, and I find it convincing for this application. It can be a fine refactoring opportunity for a later module.

**Comment by jackrusher** [comment]
One thought: once `source` is working, it might be nice to have them use it on `square` to see that it just calls `rectangle` with the argument repeated.
