### ISSUE TITLE
URL for quick intro & learning modules

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#39]
Our [quick intro](https://github.com/mhuebert/maria/blob/master/doc/quick_intro.cljs) should auto-load either from maria.cloud or maria.cloud/intro

**Comment by jackrusher** [comment]
I vote for `maria.cloud/intro`. I think the base URL should be a welcome/splash page that links to the intro and some other blah-blah about what we're trying to accomplish.

**Comment by mhuebert** [comment]
maria.cloud/intro works for me.

I can work on this, as it overlaps with some auth/persistence work I've
started.

FYI I've added 'www' as the default subdomain, necessary for some
iframe/auth reasons.

**Comment by mhuebert** [comment]
I've added a module index in `maria.curriculum` which maps gists to pathnames, accessible via `/module/:pathname` (see 06c98828424ce5b184e941a23a243059d0c01857). Closing this for now... if we want to also link `maria.cloud/intro` we can, but `maria.cloud/modules/:pathname` is more general.
