### ISSUE TITLE
Add light editor documentation to intro

### ISSUE THREAD

**Issue by jackrusher** [mhuebert/maria#43]
We should explain the `which-key` behavior, normalize vocabulary around editing, and so on.

**Comment by mhuebert** [comment]
I have added an 'Editor Quickstart' gist to the built-in modules:

![image](https://user-images.githubusercontent.com/165223/30432708-c003f70a-9962-11e7-9a7c-97a445d1e023.png)

...and copied the content into curriculum/editor_quickstart.cljs.

Coverage:

- [x] Creating code blocks
- [x] Selections
- [x] Evaluating code
- [x] The command palette
- [x] Reporting bugs
- [ ] `which-key`

(The quickstart is for people who are new to Maria but perhaps not to programming)
