### ISSUE TITLE
group is not defined in intro2.clj

### ISSUE THREAD

**Issue by martinklepsch** [mhuebert/maria#53]
<img width="713" alt="screen shot 2017-07-13 at 11 29 40" src="https://user-images.githubusercontent.com/97496/28159863-a8d2df4a-67be-11e7-9972-3844f95c7155.png">

Not sure if this is enough information but also not sure what other information I should provide :)

---

Random thought to make contributing easier: load files from a Github repo and have some kind of button to suggest improvements/changes via PRs (with Gists this is a little more tricky).

**Comment by daveliepmann** [comment]
Thanks, Martin! We renamed "group" to "layer" recently and I forgot to update all the docs. Breaking changes! :D

I definitely envision a feedback process from the tool itself.

**Comment by jackrusher** [comment]
Also, the intro curriculum is in Github [here](https://github.com/mhuebert/maria/blob/master/doc/quick_intro.cljs).

**Comment by daveliepmann** [comment]
I fixed the intro in 45f17b2bbc8064bc90e5464d0214474587652493 and, in parallel, fixed the gist. I also removed a lot of cruft from the autoload intro while I was there.

**Comment by martinklepsch** [comment]
@daveliepmann neat! And thanks for updating here :))
