### ISSUE TITLE
Don't show which-key if terminal command has been reached

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#55]
Currently the which-key window remains open regardless of whether a command has been reached. For example, if one holds `command` and presses `return/enter`, the expression at point is evaluated, and then the which-key window is displayed *after* evaluation. Is this what we want?

**Comment by mhuebert** [comment]
*The previous fix only removed which-key after executing a command if it was already visible... I just pushed another update to prevent it from popping up _after_ a command is executed.
