### ISSUE TITLE
Better file/gist functionality

### ISSUE THREAD

**Issue by mhuebert** [mhuebert/maria#64]
Basic save os been working quite well for me but some improvements would be nice:

- [x] instead of using github's 'fork' api, make copies of gists instead (because you can only fork a repo once, trying to fork a second time leads to weird results).
- [x] handle gist data locally such that the latest persisted data is used in the `list gists` view. currently if you save a gist with a new title, the old title still shows up in list view.
- [x] expose link to GitHub gist page
- [x] allow removal of local docs
- [x] remember recently viewed gists

**Comment by daveliepmann** [comment]
- [ ] mouseover/hover hints on buttons
