### ISSUE TITLE
Page <title> reset

### ISSUE THREAD

**Issue by pesterhazy** [mhuebert/maria#66]
Opening https://www.maria.cloud/new, the page initially displays the tab title "Maria", but then the title tag in the head gets reset to "". Chrome shows "https://www.maria.cloud/new" in the tab title.

**Comment by mhuebert** [comment]
Good catch, the title should update to be the currently edited filename (for persisted gists) but in this case, when you create a blank document, there is no filename. It should default to 'Maria' in that case.
