### ISSUE TITLE
Auto-pairing of parens

### ISSUE THREAD

**Issue by pesterhazy** [mhuebert/maria#69]
In this scenario

```
|()
```

if I type `(` only an opening parenthesis is added. But if I do the same anywhere else in the line, the closing parenthesis is automatically inserted. Is this difference intentional?

**Comment by mhuebert** [comment]
not intentional -- we're tracking it in #33.

It boils down to the fact that we haven't implemented this feature ourselves yet, and CodeMirror's bracket addon has this weird behavior.

**Comment by pesterhazy** [comment]
Ah I missed that, thanks!
