### ISSUE TITLE
Availability of REPL/helper functions across namespaces

### ISSUE THREAD

**Issue by mhuebert** [mhuebert/maria#7]
### The problem

Until now we have been using `maria.user` as a namespace to hold functions that we want to make accessible to users. But what happens if a user creates a new namespace? Then our helper functions disappear.

#### REPL Specials 

One way to make a function available across all namespaces is to use `cljs-live.eval/defspecial` to define a 'REPL special' function. But REPL-specials are handled differently from ordinary functions because (a) they receive the compiler state and environment as its first two arguments, (b) they are expected to return a map containing a :value or :error key, and (c) they are not evaluated by the self-hosted compiler. So they are not an ideal way to refer more _ordinary_ functions into user-space.

#### `def` in cljs.core

In Clojure-land, [lucidity/inject](https://github.com/zcaudate/lucidity/blob/master/src/lucid/core/inject.clj) (previously 'vinyasa') is a utility for referring names into clojure.core. It uses `intern`, which is not implemented in ClojureScript, but is in [planck](https://github.com/mfikes/planck/blob/6555ccf9435cb7f5bf93f6ac20efbc75fd5423ab/planck-cljs/src/planck/repl.cljs#L1781), using `def` under the hood. The approach seems reasonable. I have written a simple version of `inject` and will push it soon.

One downside to `defs` in cljs.core is that the `doc` will indicate that the function lives in `cljs.core`, which is misleading. We can get around that by copying the original var's metadata into the compiler state; then, `(doc my-referred-var)` will show `original-namespace/my-referred-var`.

Relatedly, we may want to look at modifying `dir` to distinguish between names that have been injected into a namespace, vs. names that were originally defined there.

#### Language Levels
cc: @jackrusher 

This ties into the  'language levels' idea - that we can morph namespaces to accommodate users of different skill levels. What should a command like `(language-level :beginner-1)` do? Probably some combination of (1) refer helper names into scope, and (2) stub/wrap existing functions to limit the names available to a user in a friendly way (eg. display a message if a user tries to use a real clojure function that isn't available yet for their level). In order to not affect lower-level code, we should probably *not* modify `cljs.core` functions directly for these purposes, and instead limit the effects of `language-level` to the current namespace.

**Comment by daveliepmann** [comment]
The lack of `doc` or `what-is` might also be a good opportunity to introduce namespaces.

**Comment by mhuebert** [comment]
I think `doc` and `what-is` will remain global, because they both participate in the repl-special system. But yeah, for anything else (shapes, etc.), maybe by the time users have figured out how to switch to a namespace, they are ready to learn how to require names into that space. Unless we think of other REPL commands or 'standard maria library' stuff that should be available everywhere.

**Comment by mhuebert** [comment]
The `inject` repl-special will now copy a var from one namespace to another, similar to (but even more aggressive than) vinyasa/lucidity tools.
