### ISSUE TITLE
Triangles use wrong height value

### ISSUE THREAD

**Issue by ann-marieboehme** [mhuebert/maria#75]
I've drawn three triangles that are shifted by the same distance as the (bottom) vertice of the triangles. So their bottom edges should touch each other but that didn't work as I expected: 

![bildschirmfoto 2017-07-24 um 10 45 05](https://user-images.githubusercontent.com/30405948/28527045-a2b0e62e-7089-11e7-88ad-d84bc0851e6a.png)

```clojure
(layer
  (position 0 0 (colorize "paleturquoise" (triangle 70)))
  (position 30 30 (colorize "mediumturquoise" (triangle 40)))
  (position 70 10 (colorize "plum" (triangle 60)))
  (position 96 36 (colorize "mediumorchid" (triangle 34)))
  (position 130 20 (colorize "aquamarine" (triangle 50)))
  (position 152 42 (colorize "turquoise" (triangle 28)))
  #_(position 150 150 (colorize "yellow" (square 10))))
```

I found out that if I draw something under the triangles they are fully shown. 
(If you remove the comment before the last line you can see that the edges of the triangles are touching each other.)

**Comment by jackrusher** [comment]
It turns out the triangles were being placed correctly, but a bug was causing them to be clipped in such a way that their bases were not visible. Fix pushed to git, should show up the next time we do a production build.

Thanks for the report!
