### ISSUE TITLE
Links in Markdown

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#84]
It would be nice to be able to add links using Markdown syntax.

**Comment by jackrusher** [comment]
If we don't support linking to images yet, that would also be nice. :)

**Comment by mhuebert** [comment]
links and images are now supported via entering the ordinary markdown syntax, and then pressing the space bar. Press backspace immediately after an image or link to edit.

```
[a link](url)
![an image](url)
```

When a link is clicked, the cursor is moved into the link (eg. for editing the text), while a small box hovers below it with a clickable url for navigation.
