### ISSUE TITLE
Redefine function error

### ISSUE THREAD

**Issue by ArthurYidi** [mhuebert/maria#87]
Maria doesn't allow you to redefine an imported function, in this case `maria.user.shapes/square`. 

<img width="225" alt="screen shot 2017-08-30 at 5 45 55 pm" src="https://user-images.githubusercontent.com/1154353/29901136-2167d3d6-8dab-11e7-910e-68943a1197e7.png">

It would be great to provide a more friendly error message.

**Comment by mhuebert** [comment]
Thanks for this! In the `dev` channel (https://dev.maria.cloud) we currently show the data of the error (there was a bug causing that empty list that you see), but we still lack messages for these warning types.

<img width="406" alt="screen shot 2017-08-31 at 10 28 53 am" src="https://user-images.githubusercontent.com/165223/29914003-3b1c162a-8e37-11e7-8097-4d55fae74843.png">

**Missing warning messages:**

- [ ] `:ns-var-clash`
- [ ] `:redef`

**Comment by mhuebert** [comment]
Fixed - see sample: https://dev.maria.cloud/gist/dbe95c24d08a9b00164ff86657b427e4?eval=true

<img width="859" alt="screen shot 2017-08-31 at 1 40 19 pm" src="https://user-images.githubusercontent.com/165223/29921473-f99c0280-8e51-11e7-87e6-c51a4ec08423.png">

**Comment by ArthurYidi** [comment]
👍
