### ISSUE TITLE
(what-is (circle 50)) => "a map..." in dev

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#89]
In dev:
```
(what-is (circle 50))
=> "a map: a collection of key/value pairs, where each key 'maps' to its corresponding value"
```

This seems to be a regression from prod:
```
(what-is (circle 50))
"a shape: some geometry that Maria can draw"
```

**Comment by mhuebert** [comment]
Yes.. I changed shapes to be protocol-driven without also updating the
what-is side. I also want to take another pass at how we annotate types
with what-is metadata and can fix this then.
