### ISSUE TITLE
Strings are undeclared vars

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#90]
In dev:
```
"puppy"
=> `puppy` hasn't been defined! Perhaps there is a misspelling, or this expression depends on a name that has not yet been evaluated?
(:undeclared-var)
```

**Comment by mhuebert** [comment]
Ah, what's happening here is a bug with M1- selections. It is evaluating exactly what is shown as selected, which is the inside of the string, even when the cursor on the edge of the string. I can push a fix for this soon.
