### ISSUE TITLE
New command: show/open recent gists

### ISSUE THREAD

**Issue by pedrorgirardi** [mhuebert/maria#94]
It would be very nice to have a command to show/open recent gists, that way we could switch between gists without leaving the editor.

**Comment by mhuebert** [comment]
Added this, bound to Command/Control-O:

<img width="334" alt="screen shot 2017-09-12 at 3 34 32 pm" src="https://user-images.githubusercontent.com/165223/30328534-ea71d924-97cf-11e7-94ce-cfe7a576ed90.png">

Currently it only shows+filters 'recently opened' docs. In the future we could expand to show more gists/etc, but that will wait till we further develop ideas around persistence, namespaces and so on.
