### ISSUE TITLE
autocomplete: support namespace aliases

### ISSUE THREAD

**Issue by mhuebert** [mhuebert/maria#96]
- [x] Recognize namespace aliases and show scoped completions

**Comment by daiyi** [comment]
I came here to replace that `clojure.string/replace` was not being included in autocorrect, but while making this demo it started working! haha

![string/replace](https://user-images.githubusercontent.com/1589186/30880511-19576450-a303-11e7-8979-e16037130e32.gif)

It isn't highlighting it red like with other valid functions though, so maybe there _is_ a bug?

**Comment by mhuebert** [comment]
@daiyi alright, not sure what might have been happening! but glad it is working now.

it also works for namespace aliases, eg

![image](https://user-images.githubusercontent.com/165223/30884566-705e2236-a310-11e7-9f4a-186dee3ab118.png)

the highlighting is just a built-in CodeMirror highlighting mode which has some quirks. at some point we would like to fix this but it means re-implementing highlighting ourselves :-).
