### ISSUE TITLE
sticky top-nav, or other means of indicating command palette

### ISSUE THREAD

**Issue by mhuebert** [mhuebert/maria#99]
It's not clear how to get to the command palette. May be sufficient to make the top nav sticky (the ? icon opens the command palette)

**Comment by pedrorgirardi** [comment]
I like the sticky top-nav idea. Do you see any problem?

I don't think the question mark icon for the command palette does a good job on communicating its purpose. I find it to be very common and usually used for "help", so maybe a different icon could help too. Finding a good icon is hard though.

**Comment by jackrusher** [comment]
There's always the option of not using an icon at all, but rather using a little bit of text to mark the option.

**Comment by pedrorgirardi** [comment]
I agree @jackrusher. Very good point.

**Comment by mhuebert** [comment]
Many thanks for the feedback.

I've added text labels to some commands, and keyboard shortcuts to tooltips where applicable:

![image](https://user-images.githubusercontent.com/165223/30425057-33bf44f8-9948-11e7-99c3-210148e82a0e.png)

Also made the top-bar fixed, and darkened when the page is scrolled:

![image](https://user-images.githubusercontent.com/165223/30425098-5a2c09dc-9948-11e7-8a2f-0e43e8390f5d.png)

I've pushed this to maria.cloud.

For reference, some of the links I found looking into text+icons:

Nielsen group - https://www.nngroup.com/articles/icon-usability/ 

- universally understood icons are rare
- users simply don't click icons that they don't understand
- icons need a text label

Orbitz - https://www.uie.com/brainsparks/2006/02/20/orbitz-cant-get-a-date/

- users learn the _location_ of buttons more readily than their content (this explains why I find the [default ProseMirror menus](http://prosemirror.net/examples/basic/) problematic: buttons appear and disappear based on context, instead of remaining visible, but fading out, so you can't rely on position)

Bruce Tognazzini, Apple UI, talking about balancing the tensions of friendly vs utilitarian (http://www.asktog.com/columns/044top10docksucks.html):

> Contrary to my previously-held position, I no longer believe Apple should get rid of the Dock. It's just too pretty there in the store, and it does help set Mac apart from the more utilitarian appearance of Windows... You want that in sales. You want a visibly-apparent manifestation of the personality of the underlying technology...
>
> A certain class of Apple users—those who check their email once or twice a week and sometimes need to print an attached photo—may need nothing more than the Dock.
>
> The rest of us need more powerful tools, so, Apple, leave the Dock as the smashing demo it is, but also supply some serious, information-dense tools. You have the talent and wherewithal to make such tools as attractive as the Dock if only you will cease seeing this one single object as a complete solution.

**Comment by pedrorgirardi** [comment]
Thank you @mhuebert! I really liked the changes and thanks for the references.

**Comment by jackrusher** [comment]
I'm reminded of the idea to record the relevant research in the Wiki, which I've not really done much. :( But, yes, all of those sources feed into my general ambivalence toward icon-oriented interfaces.

**Comment by pedrorgirardi** [comment]
You reckon it's a good idea to create a new page in the wiki with design guideline references?

**Comment by mhuebert** [comment]
I've added these to this page: https://github.com/mhuebert/maria/wiki/Background-reading
